### ISSUE TITLE
End Dimension Crash - mosilez

### ISSUE THREAD

**Issue by Hir0shiyt** [Hir0shiyt/RandomEnchants2#2]
Can find comments at: https://legacy.curseforge.com/minecraft/mc-mods/random-enchants-2#c11
 Similar issue, trying to hit the ender dragon or any of the healing pillars with arrows gives me a ticking crash. attacking anything else with arrows doesn't give me any issues as far as i know.

and: https://legacy.curseforge.com/minecraft/mc-mods/random-enchants-2#c9

 1.20.1 and it happened with an unenchanted bow, but once i uninstalled the mod, i was able to attacked the dragon and end beacons.. 

Log Given:

Time: 2023-10-08 00:40:08Time: 2023-10-08 00:40:08Description: Ticking entity
java.lang.ClassCastException: class net.minecraft.world.entity.boss.EnderDragonPart cannot be cast to class net.minecraft.world.entity.LivingEntity (net.minecraft.world.entity.boss.EnderDragonPart and net.minecraft.world.entity.LivingEntity are in module minecraft@1.20.1 of loader 'TRANSFORMER' @5f68eec6) at net.hir0shiyt.randomenchants2.enchantment.Disarm.onArrowImpact(Disarm.java:95) ~[randomenchants2-3.5-1.20.1.jar%23663!/:3.5-1.20.1] {re:classloading} at net.hir0shiyt.randomenchants2.enchantment.__Disarm_onArrowImpact_ProjectileImpactEvent.invoke(.dynamic) ~[randomenchants2-3.5-1.20.1.jar%23663!/:3.5-1.20.1] {re:classloading,pl:eventbus:B} at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2387!/:?] {} at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?] {} at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?] {} at net.minecraftforge.event.ForgeEventFactory.onProjectileImpactResult(ForgeEventFactory.java:677) ~[forge-1.20.1-47.1.46-universal.jar%23745!/:?] {re:mixin,re:classloading,pl:mixin:APP:aether.mixins.json:common.ForgeEventFactoryMixin,pl:mixin:A} at net.minecraft.world.entity.projectile.AbstractArrow.m_8119_(AbstractArrow.java:192) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:l2library.mixins.json:AbstractArrowMixin,pl:mixin:APP:aether.mixins.json:common.AbstractArrowMixin,pl:mixin:APP:skilltree.mixins.json:minecraft/MixinAbstractArrow,pl:mixin:A} at net.mcreator.realmrpgwyrms.entity.EnderWyrmFireballEntity.m_8119_(EnderWyrmFireballEntity.java:83) ~[realmrpg_dragon_wyrms_0.9.0_forge_1.20.1.jar%23666!/:?] {re:classloading,pl:runtimedistcleaner:A} at net.minecraft.client.multiplayer.ClientLevel.m_104639_(ClientLevel.java:274) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_clientworldclass,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_clientworldclass,pl:mixin:APP:citadel.mixins.json:client.ClientLevelMixin,pl:mixin:APP:blue_skies.mixins.json:ClientLevelMixin,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:enhancedcelestials.mixins.json:client.MixinClientWorld,pl:mixin:A,pl:runtimedistcleaner:A} at net.minecraft.entity.TickOptimizer.handleGuardEntityTick(TickOptimizer.java:62) ~[NoSeeNoTick-2.0.0-1.20.1.jar%23643!/:2.0.0-build.9999] {re:mixin,re:classloading} at net.minecraft.entity.TickOptimizer.entityTicking(TickOptimizer.java:25) ~[NoSeeNoTick-2.0.0-1.20.1.jar%23643!/:2.0.0-build.9999] {re:mixin,re:classloading} at net.minecraft.world.level.Level.m_46653_(Level.java:3041) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:LevelMixin,pl:mixin:APP:mixins.hammerlib.json:LevelMixin,pl:mixin:APP:sereneseasons.mixins.json:MixinLevel,pl:mixin:APP:aether.mixins.json:common.accessor.LevelAccessor,pl:mixin:APP:noseenotick.mixins.json:EntityTickMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinWorld,pl:mixin:A} at net.minecraft.client.multiplayer.ClientLevel.m_194182_(ClientLevel.java:256) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_clientworldclass,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_clientworldclass,pl:mixin:APP:citadel.mixins.json:client.ClientLevelMixin,pl:mixin:APP:blue_skies.mixins.json:ClientLevelMixin,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:enhancedcelestials.mixins.json:client.MixinClientWorld,pl:mixin:A,pl:runtimedistcleaner:A} at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?] {re:classloading} at net.minecraft.client.multiplayer.ClientLevel.m_104804_(ClientLevel.java:254) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_clientworldclass,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_clientworldclass,pl:mixin:APP:citadel.mixins.json:client.ClientLevelMixin,pl:mixin:APP:blue_skies.mixins.json:ClientLevelMixin,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:enhancedcelestials.mixins.json:client.MixinClientWorld,pl:mixin:A,pl:runtimedistcleaner:A} at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1814) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A} at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1112) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A} at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A} at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.1.46.jar:?] {re:classloading,pl:runtimedistcleaner:A} at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {} at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {} at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {} at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {} at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.1.46.jar:?] {} at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.1.46.jar:?] {} at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.1.46.jar:?] {} at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {} at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {} at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {} at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {} at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {} at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {} at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {} at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

**Comment by Hir0shiyt** [comment]
Found cause: Disarm Enchantment

**Comment by Hir0shiyt** [comment]
Fixed on:

1.20.1 [3.7]
1.19.4 [3.8]
1.19.3 [3.9]
1.19.2 [4.0]
1.18.2 [3.0.2] fix
1.17.1 [4.1]
